"""Create Salesforce Connected App for OBO (JWT Bearer flow).

Uses the classic ConnectedApp metadata type (not ECA) because:
- ConnectedApp metadata supports the `certificate` field for digital signatures
- ECA metadata does NOT support certificate upload (it's UI-only, like PKCE)
- JWT Bearer flow works identically with classic Connected Apps

Creates a Connected App with:
1. X.509 certificate uploaded for digital signature verification
2. OAuth scopes: Api, RefreshToken
3. Admin-approved pre-authorization (isAdminApproved=true)

After deployment, the script:
- Retrieves the auto-generated Consumer Key
- Assigns profiles via the SetupEntityAccess API

Prerequisites:
- Salesforce CLI (sf) installed and authenticated to the target org
- Azure CLI (az) installed and signed in (for profile assignment via REST API)
- X.509 certificate PEM file (generated by openssl)

Usage:
    python scripts/setup-sf-obo-eca.py --org my-dev-org --email admin@example.com --cert certs/sf-jwt-bearer.crt
"""

import argparse
import json
import os
import subprocess
import sys
import tempfile

os.environ.setdefault("PYTHONIOENCODING", "utf-8")

DEFAULT_APP_NAME = "Identity_PoC_OBO_JWT"
DEFAULT_APP_LABEL = "Identity PoC OBO JWT"


def run(cmd: str, parse_json: bool = False, cwd: str | None = None):
    """Run a shell command and return stdout."""
    result = subprocess.run(
        cmd, capture_output=True, text=True, shell=True,
        encoding="utf-8", errors="replace",
        env={**os.environ, "MSYS_NO_PATHCONV": "1"},
        cwd=cwd,
    )
    if result.returncode != 0:
        if result.stderr:
            print(f"  stderr: {result.stderr[:500]}")
        return None
    out = result.stdout.strip()
    if not out:
        return None
    if parse_json:
        try:
            return json.loads(out)
        except json.JSONDecodeError:
            return None
    return out


def _init_sfdx_project(work_dir: str):
    """Create a minimal sfdx-project.json + force-app dir so sf CLI commands work."""
    project_json = os.path.join(work_dir, "sfdx-project.json")
    if not os.path.exists(project_json):
        with open(project_json, "w") as f:
            json.dump({
                "packageDirectories": [{"path": "force-app", "default": True}],
                "namespace": "",
                "sfdcLoginUrl": "https://login.salesforce.com",
                "sourceApiVersion": "62.0",
            }, f, indent=2)
    os.makedirs(os.path.join(work_dir, "force-app", "main", "default"), exist_ok=True)


def check_app_exists(org: str, app_name: str) -> bool:
    """Check if the ConnectedApp already exists by trying to retrieve its metadata."""
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as check_dir:
        _init_sfdx_project(check_dir)
        result = run(
            f'sf project retrieve start --metadata "ConnectedApp:{app_name}" '
            f"-o {org}",
            cwd=check_dir,
        )
        if result is None:
            return False
        meta_path = os.path.join(
            check_dir, "force-app", "main", "default",
            "connectedApps", f"{app_name}.connectedApp-meta.xml",
        )
        return os.path.exists(meta_path)


def generate_connected_app(work_dir: str, app_name: str, app_label: str,
                           email: str, cert_base64: str):
    """Generate ConnectedApp metadata XML with certificate for JWT Bearer.

    Uses the classic ConnectedApp metadata type which supports:
    - certificate: X.509 public cert (base64, single line, no PEM headers)
    - isAdminApproved: enables pre-authorization policy
    - scopes: OAuth scopes (Api, RefreshToken)
    """
    _init_sfdx_project(work_dir)
    print(f"  Generating ConnectedApp metadata for '{app_label}'...")

    app_xml = f"""\
<?xml version="1.0" encoding="UTF-8"?>
<ConnectedApp xmlns="http://soap.sforce.com/2006/04/metadata">
    <contactEmail>{email}</contactEmail>
    <label>{app_label}</label>
    <oauthConfig>
        <callbackUrl>https://login.salesforce.com/services/oauth2/callback</callbackUrl>
        <certificate>{cert_base64}</certificate>
        <consumerKey></consumerKey>
        <isAdminApproved>true</isAdminApproved>
        <scopes>Api</scopes>
        <scopes>RefreshToken</scopes>
    </oauthConfig>
    <oauthPolicy>
        <ipRelaxation>ENFORCE</ipRelaxation>
        <refreshTokenPolicy>zero</refreshTokenPolicy>
    </oauthPolicy>
</ConnectedApp>
"""
    app_dir = os.path.join(
        work_dir, "force-app", "main", "default", "connectedApps",
    )
    os.makedirs(app_dir, exist_ok=True)
    app_path = os.path.join(app_dir, f"{app_name}.connectedApp-meta.xml")
    with open(app_path, "w", encoding="utf-8") as f:
        f.write(app_xml)

    print(f"  Created: {os.path.relpath(app_path, work_dir)}")
    return app_path


def deploy_app(org: str, work_dir: str) -> bool:
    """Deploy ConnectedApp to Salesforce."""
    print("  Deploying ConnectedApp to Salesforce...")
    result = run(
        f"sf project deploy start -o {org} --source-dir force-app",
        cwd=work_dir,
    )
    if result is None:
        print("  ERROR: Failed to deploy ConnectedApp metadata")
        print("  Verify the sf CLI is authenticated and the org is accessible:")
        print(f"    sf org display -o {org}")
        return False
    print("  Deployed successfully")
    return True


def get_consumer_key(org: str, app_name: str) -> str | None:
    """Retrieve the auto-generated Consumer Key by re-retrieving the metadata."""
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as check_dir:
        _init_sfdx_project(check_dir)
        result = run(
            f'sf project retrieve start --metadata "ConnectedApp:{app_name}" -o {org}',
            cwd=check_dir,
        )
        if result is None:
            return None

        meta_path = os.path.join(
            check_dir, "force-app", "main", "default",
            "connectedApps", f"{app_name}.connectedApp-meta.xml",
        )
        if not os.path.exists(meta_path):
            return None

        with open(meta_path, "r") as f:
            content = f.read()

        # Parse the consumer key from XML
        import re
        match = re.search(r"<consumerKey>(.*?)</consumerKey>", content)
        return match.group(1) if match else None


def assign_profiles(org: str, app_name: str, profile_names: list[str]) -> int:
    """Assign profiles to the ConnectedApp for pre-authorization.

    Uses the SetupEntityAccess API to link profile PermissionSets to the
    ConnectedApp, enabling pre-authorized access for JWT Bearer flow.
    """
    # Get access token and instance URL
    org_info = run(f"sf org display -o {org} --json", parse_json=True)
    if not org_info:
        print("  ERROR: Could not get org info")
        return 0

    result_data = org_info.get("result", {})
    access_token = result_data.get("accessToken")
    instance_url = result_data.get("instanceUrl")
    if not access_token or not instance_url:
        print("  ERROR: Could not get access token or instance URL")
        return 0

    # Get ConnectedApplication ID
    tooling_result = run(
        f"sf data query -o {org} -t -q "
        f"\"SELECT Id FROM ConnectedApplication WHERE DeveloperName='{app_name}'\" "
        f"--json",
        parse_json=True,
    )
    if not tooling_result:
        print("  ERROR: Could not find ConnectedApplication in Tooling API")
        return 0

    records = tooling_result.get("result", {}).get("records", [])
    if not records:
        print("  ERROR: ConnectedApplication not found in Tooling API")
        return 0
    connected_app_id = records[0]["Id"]

    assigned = 0
    for profile_name in profile_names:
        # Get Profile ID
        profile_result = run(
            f'sf data query -o {org} -q "SELECT Id FROM Profile WHERE Name=\'{profile_name}\'" --json',
            parse_json=True,
        )
        if not profile_result:
            print(f"  WARNING: Profile '{profile_name}' not found")
            continue
        profile_records = profile_result.get("result", {}).get("records", [])
        if not profile_records:
            print(f"  WARNING: Profile '{profile_name}' not found")
            continue
        profile_id = profile_records[0]["Id"]

        # Get PermissionSet for this Profile
        perm_result = run(
            f'sf data query -o {org} -q "SELECT Id FROM PermissionSet WHERE ProfileId=\'{profile_id}\'" --json',
            parse_json=True,
        )
        if not perm_result:
            print(f"  WARNING: PermissionSet for '{profile_name}' not found")
            continue
        perm_records = perm_result.get("result", {}).get("records", [])
        if not perm_records:
            print(f"  WARNING: PermissionSet for '{profile_name}' not found")
            continue
        perm_set_id = perm_records[0]["Id"]

        # Create SetupEntityAccess
        import urllib.request
        req = urllib.request.Request(
            f"{instance_url}/services/data/v66.0/sobjects/SetupEntityAccess",
            data=json.dumps({
                "ParentId": perm_set_id,
                "SetupEntityId": connected_app_id,
            }).encode(),
            headers={
                "Authorization": f"Bearer {access_token}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(req) as resp:
                result = json.loads(resp.read())
                if result.get("success"):
                    print(f"  Assigned: {profile_name}")
                    assigned += 1
                else:
                    print(f"  FAILED: {profile_name}: {result}")
        except urllib.error.HTTPError as e:
            body = e.read().decode()
            if "DUPLICATE_VALUE" in body:
                print(f"  Already assigned: {profile_name}")
                assigned += 1
            else:
                print(f"  FAILED: {profile_name}: {body[:200]}")
        except Exception as e:
            print(f"  FAILED: {profile_name}: {e}")

    return assigned


def main():
    parser = argparse.ArgumentParser(
        description="Create Salesforce Connected App for OBO (JWT Bearer flow). "
        "Deploys ConnectedApp with X.509 certificate and assigns profiles."
    )
    parser.add_argument(
        "--org", required=True,
        help="Salesforce org alias (as authenticated with 'sf org login web')",
    )
    parser.add_argument(
        "--email", required=True,
        help="Contact email for the Connected App",
    )
    parser.add_argument(
        "--cert", required=True,
        help="Path to X.509 certificate PEM file (public cert for SF upload)",
    )
    parser.add_argument(
        "--app-name", default=DEFAULT_APP_NAME,
        help=f"ConnectedApp developer name (default: {DEFAULT_APP_NAME})",
    )
    parser.add_argument(
        "--app-label", default=DEFAULT_APP_LABEL,
        help=f"ConnectedApp display label (default: {DEFAULT_APP_LABEL})",
    )
    parser.add_argument(
        "--force", action="store_true",
        help="Deploy even if the app already exists (overwrites settings)",
    )
    args = parser.parse_args()

    # Read certificate PEM
    cert_path = os.path.abspath(args.cert)
    if not os.path.exists(cert_path):
        print(f"ERROR: Certificate file not found: {cert_path}")
        sys.exit(1)

    with open(cert_path, "r") as f:
        cert_pem = f.read().strip()

    # Strip PEM headers and join to single line for metadata
    cert_base64 = "".join(
        line for line in cert_pem.splitlines()
        if not line.startswith("-----")
    )

    print("=" * 60)
    print("  Create SF Connected App for OBO (JWT Bearer)")
    print("=" * 60)
    print(f"  Org:         {args.org}")
    print(f"  App:         {args.app_label} ({args.app_name})")
    print(f"  Certificate: {cert_path}")

    # Step 1: Check if app already exists
    print("\n--- Step 1: Check existing ConnectedApp ---")
    exists = check_app_exists(args.org, args.app_name)

    if exists and not args.force:
        print(f"  ConnectedApp '{args.app_name}' already exists in the org")
        print("  Skipping deployment (use --force to redeploy)")
    else:
        if exists and args.force:
            print(f"  App exists but --force specified, redeploying...")
        else:
            print(f"  ConnectedApp '{args.app_name}' not found -- creating...")

        # Step 2: Generate metadata
        print("\n--- Step 2: Generate ConnectedApp metadata ---")
        with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as work_dir:
            generate_connected_app(
                work_dir, args.app_name, args.app_label, args.email, cert_base64,
            )

            # Step 3: Deploy
            print("\n--- Step 3: Deploy to Salesforce ---")
            if not deploy_app(args.org, work_dir):
                sys.exit(1)

    # Step 4: Get Consumer Key
    print("\n--- Step 4: Get Consumer Key ---")
    consumer_key = get_consumer_key(args.org, args.app_name)
    if consumer_key:
        print(f"  Consumer Key: {consumer_key}")
    else:
        print("  Could not retrieve Consumer Key via metadata retrieve")

    # Step 5: Assign profiles
    print("\n--- Step 5: Assign profiles for pre-authorization ---")
    profiles_to_assign = [
        "System Administrator",
        "Standard User",
        "Standard User - No Delete",
    ]
    assigned = assign_profiles(args.org, args.app_name, profiles_to_assign)
    print(f"  {assigned} profile(s) assigned")

    # Summary
    print()
    print("=" * 60)
    print("  OBO Connected App Setup Complete!")
    print("=" * 60)
    print()
    if consumer_key:
        print(f"  Consumer Key: {consumer_key}")
        print()
        print("  Set it in azd:")
        print(f"    azd env set SF_CONNECTED_APP_CLIENT_ID \"{consumer_key}\"")
    else:
        print("  MANUAL STEP - Get Consumer Key:")
        print(f"    SF Setup -> App Manager -> {args.app_label}")
        print("    -> Manage Consumer Details -> Copy Consumer Key")
        print("    Then run:")
        print("      azd env set SF_CONNECTED_APP_CLIENT_ID <consumer-key>")
    print()
    print("  Next steps:")
    print("    1. python scripts/set-sf-federation-id.py --org my-dev-org")
    print("    2. azd env set SF_AUTH_MODE obo")
    print("    3. azd env set SF_INSTANCE_URL https://<your-org>.my.salesforce.com")
    print("    4. azd up")


if __name__ == "__main__":
    main()
